<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Medication;
use Illuminate\Support\Str;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $medications = [
            // Critical Stock Items (≤5 units)
            [
                'name' => 'Paracetamol 500mg',
                'generic_name' => 'Acetaminophen',
                'category' => 'Analgesics',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'manufacturer' => 'Shelys Pharmaceuticals',
                'unit_price' => 0.50,
                'stock_quantity' => 2,
                'reorder_level' => 50,
                'expiry_date' => '2025-12-31',
                'batch_number' => 'PAR2024001',
                'is_active' => true,
            ],
            [
                'name' => 'Amoxicillin 250mg',
                'generic_name' => 'Amoxicillin',
                'category' => 'Antibiotics',
                'dosage_form' => 'Capsule',
                'strength' => '250mg',
                'manufacturer' => 'Cosmos Pharmaceuticals',
                'unit_price' => 1.20,
                'stock_quantity' => 3,
                'reorder_level' => 30,
                'expiry_date' => '2025-08-15',
                'batch_number' => 'AMX2024002',
                'is_active' => true,
            ],
            [
                'name' => 'Ibuprofen 400mg',
                'generic_name' => 'Ibuprofen',
                'category' => 'NSAIDs',
                'dosage_form' => 'Tablet',
                'strength' => '400mg',
                'manufacturer' => 'Zenufa Laboratories',
                'unit_price' => 0.75,
                'stock_quantity' => 1,
                'reorder_level' => 40,
                'expiry_date' => '2025-10-20',
                'batch_number' => 'IBU2024003',
                'is_active' => true,
            ],
            [
                'name' => 'Metformin 500mg',
                'generic_name' => 'Metformin HCl',
                'category' => 'Antidiabetics',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'manufacturer' => 'Keko Pharmaceuticals',
                'unit_price' => 0.80,
                'stock_quantity' => 4,
                'reorder_level' => 25,
                'expiry_date' => '2025-11-30',
                'batch_number' => 'MET2024004',
                'is_active' => true,
            ],
            [
                'name' => 'Azithromycin 250mg',
                'generic_name' => 'Azithromycin',
                'category' => 'Antibiotics',
                'dosage_form' => 'Tablet',
                'strength' => '250mg',
                'manufacturer' => 'Meditech Pharmaceuticals',
                'unit_price' => 2.50,
                'stock_quantity' => 5,
                'reorder_level' => 20,
                'expiry_date' => '2025-09-15',
                'batch_number' => 'AZI2024005',
                'is_active' => true,
            ],

            // Low Stock Items (6-10 units)
            [
                'name' => 'Omeprazole 20mg',
                'generic_name' => 'Omeprazole',
                'category' => 'Proton Pump Inhibitors',
                'dosage_form' => 'Capsule',
                'strength' => '20mg',
                'manufacturer' => 'Shelys Pharmaceuticals',
                'unit_price' => 1.50,
                'stock_quantity' => 8,
                'reorder_level' => 30,
                'expiry_date' => '2025-07-25',
                'batch_number' => 'OME2024006',
                'is_active' => true,
            ],
            [
                'name' => 'Cetirizine 10mg',
                'generic_name' => 'Cetirizine HCl',
                'category' => 'Antihistamines',
                'dosage_form' => 'Tablet',
                'strength' => '10mg',
                'manufacturer' => 'Cosmos Pharmaceuticals',
                'unit_price' => 0.60,
                'stock_quantity' => 6,
                'reorder_level' => 35,
                'expiry_date' => '2025-12-10',
                'batch_number' => 'CET2024007',
                'is_active' => true,
            ],
            [
                'name' => 'Diclofenac 50mg',
                'generic_name' => 'Diclofenac Sodium',
                'category' => 'NSAIDs',
                'dosage_form' => 'Tablet',
                'strength' => '50mg',
                'manufacturer' => 'Zenufa Laboratories',
                'unit_price' => 0.90,
                'stock_quantity' => 9,
                'reorder_level' => 25,
                'expiry_date' => '2025-06-30',
                'batch_number' => 'DIC2024008',
                'is_active' => true,
            ],
            [
                'name' => 'Amlodipine 5mg',
                'generic_name' => 'Amlodipine Besylate',
                'category' => 'Antihypertensives',
                'dosage_form' => 'Tablet',
                'strength' => '5mg',
                'manufacturer' => 'Keko Pharmaceuticals',
                'unit_price' => 1.10,
                'stock_quantity' => 7,
                'reorder_level' => 20,
                'expiry_date' => '2025-08-05',
                'batch_number' => 'AML2024009',
                'is_active' => true,
            ],
            [
                'name' => 'Ciprofloxacin 500mg',
                'generic_name' => 'Ciprofloxacin HCl',
                'category' => 'Antibiotics',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'manufacturer' => 'Meditech Pharmaceuticals',
                'unit_price' => 1.80,
                'stock_quantity' => 10,
                'reorder_level' => 15,
                'expiry_date' => '2025-09-20',
                'batch_number' => 'CIP2024010',
                'is_active' => true,
            ],

            // Liquid Medications (Low Stock)
            [
                'name' => 'Paracetamol Syrup',
                'generic_name' => 'Paracetamol',
                'category' => 'Analgesics',
                'dosage_form' => 'Syrup',
                'strength' => '120mg/5ml',
                'manufacturer' => 'Shelys Pharmaceuticals',
                'unit_price' => 3.50,
                'stock_quantity' => 4,
                'reorder_level' => 20,
                'expiry_date' => '2025-05-15',
                'batch_number' => 'PARS2024011',
                'is_active' => true,
            ],
            [
                'name' => 'Amoxicillin Suspension',
                'generic_name' => 'Amoxicillin',
                'category' => 'Antibiotics',
                'dosage_form' => 'Suspension',
                'strength' => '125mg/5ml',
                'manufacturer' => 'Cosmos Pharmaceuticals',
                'unit_price' => 4.20,
                'stock_quantity' => 3,
                'reorder_level' => 15,
                'expiry_date' => '2025-07-10',
                'batch_number' => 'AMXS2024012',
                'is_active' => true,
            ],
            [
                'name' => 'Cough Syrup (Dextromethorphan)',
                'generic_name' => 'Dextromethorphan HBr',
                'category' => 'Antitussives',
                'dosage_form' => 'Syrup',
                'strength' => '15mg/5ml',
                'manufacturer' => 'Zenufa Laboratories',
                'unit_price' => 5.00,
                'stock_quantity' => 2,
                'reorder_level' => 12,
                'expiry_date' => '2025-04-30',
                'batch_number' => 'COUGH2024013',
                'is_active' => true,
            ],

            // Injectable Medications (Critical Stock)
            [
                'name' => 'Insulin (Human)',
                'generic_name' => 'Human Insulin',
                'category' => 'Antidiabetics',
                'dosage_form' => 'Injection',
                'strength' => '100IU/ml',
                'manufacturer' => 'Meditech Pharmaceuticals',
                'unit_price' => 25.00,
                'stock_quantity' => 1,
                'reorder_level' => 10,
                'expiry_date' => '2025-03-20',
                'batch_number' => 'INS2024014',
                'is_active' => true,
            ],
            [
                'name' => 'Diclofenac Injection',
                'generic_name' => 'Diclofenac Sodium',
                'category' => 'NSAIDs',
                'dosage_form' => 'Injection',
                'strength' => '75mg/3ml',
                'manufacturer' => 'Keko Pharmaceuticals',
                'unit_price' => 3.80,
                'stock_quantity' => 5,
                'reorder_level' => 15,
                'expiry_date' => '2025-06-15',
                'batch_number' => 'DICINJ2024015',
                'is_active' => true,
            ],

            // Topical Medications (Low Stock)
            [
                'name' => 'Hydrocortisone Cream',
                'generic_name' => 'Hydrocortisone',
                'category' => 'Topical Corticosteroids',
                'dosage_form' => 'Cream',
                'strength' => '1%',
                'manufacturer' => 'Shelys Pharmaceuticals',
                'unit_price' => 6.50,
                'stock_quantity' => 8,
                'reorder_level' => 20,
                'expiry_date' => '2025-11-05',
                'batch_number' => 'HYD2024016',
                'is_active' => true,
            ],
            [
                'name' => 'Clotrimazole Cream',
                'generic_name' => 'Clotrimazole',
                'category' => 'Antifungals',
                'dosage_form' => 'Cream',
                'strength' => '1%',
                'manufacturer' => 'Cosmos Pharmaceuticals',
                'unit_price' => 4.75,
                'stock_quantity' => 6,
                'reorder_level' => 18,
                'expiry_date' => '2025-08-25',
                'batch_number' => 'CLO2024017',
                'is_active' => true,
            ],

            // Emergency Medications (Critical Stock)
            [
                'name' => 'Epinephrine Auto-Injector',
                'generic_name' => 'Epinephrine',
                'category' => 'Emergency Medications',
                'dosage_form' => 'Auto-Injector',
                'strength' => '0.3mg',
                'manufacturer' => 'Meditech Pharmaceuticals',
                'unit_price' => 45.00,
                'stock_quantity' => 2,
                'reorder_level' => 8,
                'expiry_date' => '2025-02-28',
                'batch_number' => 'EPI2024018',
                'is_active' => true,
            ],
            [
                'name' => 'Salbutamol Inhaler',
                'generic_name' => 'Salbutamol Sulfate',
                'category' => 'Bronchodilators',
                'dosage_form' => 'Inhaler',
                'strength' => '100mcg/dose',
                'manufacturer' => 'Zenufa Laboratories',
                'unit_price' => 12.50,
                'stock_quantity' => 4,
                'reorder_level' => 12,
                'expiry_date' => '2025-10-15',
                'batch_number' => 'SAL2024019',
                'is_active' => true,
            ],

            // Additional Low Stock Items
            [
                'name' => 'Atorvastatin 20mg',
                'generic_name' => 'Atorvastatin Calcium',
                'category' => 'Statins',
                'dosage_form' => 'Tablet',
                'strength' => '20mg',
                'manufacturer' => 'Keko Pharmaceuticals',
                'unit_price' => 2.20,
                'stock_quantity' => 9,
                'reorder_level' => 25,
                'expiry_date' => '2025-12-20',
                'batch_number' => 'ATO2024020',
                'is_active' => true,
            ],
        ];

        foreach ($medications as $medication) {
            Medication::create($medication);
        }

        $this->command->info('Created ' . count($medications) . ' medications with various stock levels for testing low stock reports.');
        $this->command->info('Critical stock items (≤5 units): ' . collect($medications)->where('stock_quantity', '<=', 5)->count());
        $this->command->info('Low stock items (6-10 units): ' . collect($medications)->whereBetween('stock_quantity', [6, 10])->count());
    }
}