import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Printer, AlertTriangle, Package } from 'lucide-react';
import { format } from 'date-fns';
import api from '@/lib/api';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';

interface Medication {
  id: string;
  name: string;
  generic_name?: string;
  dosage_form?: string;
  strength?: string;
  stock_quantity?: number;
  quantity_in_stock?: number;
  reorder_level: number;
  unit_price: number;
  manufacturer?: string;
}

export default function LowStockInventoryReport() {
  const { user } = useAuth();
  const [medications, setMedications] = useState<Medication[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchMedications();
  }, []);

  const fetchMedications = async () => {
    try {
      setLoading(true);
      const response = await api.get('/pharmacy/medications');
      setMedications(response.data.medications || []);
    } catch (error) {
      console.error('Error fetching medications:', error);
      toast.error('Failed to load medications');
    } finally {
      setLoading(false);
    }
  };

  const lowStockMeds = medications.filter(m => 
    (m.stock_quantity || m.quantity_in_stock || 0) <= m.reorder_level
  );

  const handlePrint = async () => {
    if (lowStockMeds.length === 0) {
      toast.info('No low stock items to print');
      return;
    }

    // Fetch logo URL
    let logoUrl = '';
    try {
      const response = await api.get('/settings/logo');
      logoUrl = response.data.logo_url || '';
    } catch (error) {
      console.log('No custom logo found, using default');
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow popups to print');
      return;
    }

    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Low Stock Inventory Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          .logo-container { text-align: center; margin-bottom: 20px; }
          .logo { width: 100px; height: 100px; margin: 0 auto 15px; }
          .logo img { width: 100%; height: 100%; object-fit: contain; }
          h1 { color: #dc2626; border-bottom: 2px solid #dc2626; padding-bottom: 10px; text-align: center; }
          .header { margin-bottom: 20px; border-top: 3px solid #000; border-bottom: 3px solid #000; padding: 20px 0; }
          .hospital-name { font-size: 28px; font-weight: bold; text-align: center; letter-spacing: 3px; color: #000; margin-bottom: 10px; }
          .date { color: #666; font-size: 14px; text-align: center; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #fee2e2; color: #991b1b; font-weight: bold; }
          tr:nth-child(even) { background-color: #f9f9f9; }
          .critical { background-color: #fef2f2 !important; }
          .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; text-align: center; }
          @media print {
            button { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          ${logoUrl ? `
            <div class="logo-container">
              <div class="logo">
                <img src="${logoUrl}" alt="Hospital Logo" />
              </div>
            </div>
          ` : ''}
          <div class="hospital-name">HASET HOSPITAL</div>
          <h1>🚨 LOW STOCK INVENTORY REPORT</h1>
          <p class="date">Generated: ${format(new Date(), 'PPpp')}</p>
          <p class="date">Generated by: ${user?.name || user?.full_name || 'Admin'}</p>
        </div>
        
        <p><strong>Total Low Stock Items:</strong> ${lowStockMeds.length}</p>
        
        <table>
          <thead>
            <tr>
              <th>Medication Name</th>
              <th>Generic Name</th>
              <th>Form</th>
              <th>Strength</th>
              <th>Current Stock</th>
              <th>Reorder Level</th>
              <th>Unit Price (TSh)</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${lowStockMeds.map(med => {
              const stock = med.stock_quantity || med.quantity_in_stock || 0;
              const isCritical = stock <= 5;
              return `
                <tr class="${isCritical ? 'critical' : ''}">
                  <td><strong>${med.name}</strong></td>
                  <td>${med.generic_name || '-'}</td>
                  <td>${med.dosage_form || 'Tablet'}</td>
                  <td>${med.strength || '-'}</td>
                  <td><strong>${stock}</strong></td>
                  <td>${med.reorder_level}</td>
                  <td>${Number(med.unit_price || 0).toFixed(2)}</td>
                  <td>${isCritical ? '🔴 CRITICAL' : '⚠️ Low'}</td>
                </tr>
              `;
            }).join('')}
          </tbody>
        </table>
        
        <div class="footer">
          <p>This report shows all medications with stock levels at or below their reorder level.</p>
          <p>Critical items (≤5 units) are highlighted in red.</p>
        </div>
        
        <button onclick="window.print()" style="margin-top: 20px; padding: 10px 20px; background: #dc2626; color: white; border: none; border-radius: 4px; cursor: pointer;">Print Report</button>
      </body>
      </html>
    `;

    printWindow.document.write(printContent);
    printWindow.document.close();
    
    toast.success('Print preview opened');
  };

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Low Stock Inventory</CardTitle>
          <CardDescription>Loading...</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center py-8">
            <Package className="h-8 w-8 animate-pulse text-muted-foreground" />
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-amber-500" />
            Low Stock Inventory
          </CardTitle>
          <CardDescription>
            {lowStockMeds.length} medication(s) below reorder level
          </CardDescription>
        </div>
        <Button onClick={handlePrint} disabled={lowStockMeds.length === 0}>
          <Printer className="h-4 w-4 mr-2" />
          Print Report
        </Button>
      </CardHeader>
      <CardContent>
        {lowStockMeds.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <Package className="h-12 w-12 mx-auto mb-2 opacity-30" />
            <p>All medications are adequately stocked</p>
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Medication</TableHead>
                <TableHead>Form</TableHead>
                <TableHead>Strength</TableHead>
                <TableHead>Current Stock</TableHead>
                <TableHead>Reorder Level</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {lowStockMeds.map((med) => {
                const stock = med.stock_quantity || med.quantity_in_stock || 0;
                const isCritical = stock <= 5;
                return (
                  <TableRow key={med.id} className={isCritical ? 'bg-red-50' : ''}>
                    <TableCell>
                      <div className="font-medium">{med.name}</div>
                      {med.generic_name && (
                        <div className="text-sm text-muted-foreground">{med.generic_name}</div>
                      )}
                    </TableCell>
                    <TableCell>{med.dosage_form || 'Tablet'}</TableCell>
                    <TableCell>{med.strength || '-'}</TableCell>
                    <TableCell className="font-semibold">{stock}</TableCell>
                    <TableCell>{med.reorder_level}</TableCell>
                    <TableCell>
                      <Badge variant={isCritical ? 'destructive' : 'secondary'}>
                        {isCritical ? 'Critical' : 'Low Stock'}
                      </Badge>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  );
}
